# Generated by Django 5.2.15 on 2026-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='depreciation_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent of purchase cost lost each depreciation period', max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_period',
            field=models.CharField(blank=True, choices=[('DAY', 'Per Day'), ('MONTH', 'Per Month'), ('YEAR', 'Per Year')], help_text='Depreciate the asset per day, month or year', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('GUARANTY', 'Guaranty'), ('WARRANTY', 'Warranty')], help_text='Whether the asset is covered by a guaranty or a warranty', max_length=20),
        ),
    ]
