# Generated by Django 5.2.15 on 2026-07-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_depreciation_percent_asset_depreciation_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warranty_years',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Length of the guaranty/warranty in years', max_digits=4, null=True),
        ),
    ]
