# Generated by Django 6.0.6 on 2026-06-18 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='climate_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='irrigation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='irrigation_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='field',
            name='slope',
            field=models.CharField(blank=True, help_text='e.g. Flat, Gentle, Steep', max_length=50),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_ph',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='FarmDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('DEED', 'Land Deed'), ('SURVEY', 'Survey Report'), ('SOIL_TEST', 'Soil Test Report'), ('WATER_TEST', 'Water Test Report'), ('LEASE', 'Lease Agreement'), ('MAP', 'Plot Map'), ('PHOTO', 'Farm Photo'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('document', models.FileField(upload_to='farm_documents/')),
                ('description', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_documents', to='farms.farm')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Farm Created'), ('FIELD_ADDED', 'Field/Plot Added'), ('CROP_PLANTED', 'Crop Planted'), ('CROP_HARVESTED', 'Crop Harvested'), ('MANAGER_CHANGED', 'Manager Changed'), ('AREA_UPDATED', 'Area Updated'), ('EQUIPMENT_ADDED', 'Equipment Added'), ('INFRASTRUCTURE', 'Infrastructure Update'), ('RECORD', 'General Record')], default='RECORD', max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('related_model', models.CharField(blank=True, help_text='e.g. Field, Crop, Asset', max_length=100)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='farms.farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_history_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farm histories',
                'ordering': ['-event_date'],
            },
        ),
    ]
