# Generated by Django 5.2.15 on 2026-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_farm_climate_zone_farm_established_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[("PLOT", "Plot"), ("BLOCK", "Block"), ("SECTION", "Section")],
                default="PLOT",
                max_length=20,
            ),
        ),
    ]
