# Generated by Django 5.2.15 on 2026-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_field_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="block_name",
            field=models.CharField(
                blank=True,
                help_text="Block / section name within the field",
                max_length=150,
            ),
        ),
    ]
