# Generated by Django 5.2.15 on 2026-07-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_field_block_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='check_in_radius',
            field=models.IntegerField(default=100, help_text='Radius in meters for GPS check-in validation. Default 100m'),
        ),
    ]
