# Generated by Django 5.2.15 on 2026-06-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="half_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
