# Generated by Django 5.2.15 on 2026-07-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslip_half_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='payment_photo',
            field=models.ImageField(blank=True, help_text='Optional bill/receipt photo for the payout (online transaction proof)', null=True, upload_to='payslips/'),
        ),
    ]
