# Generated by Django 5.2.15 on 2026-06-17 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agronomy", "0001_initial"),
        ("farms", "0001_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="agronomy.crop",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_advance",
            field=models.BooleanField(
                default=False, help_text="Advance payment to a vendor"
            ),
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_centers",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LABOUR", "Labour"),
                            ("INPUTS", "Inputs"),
                            ("FUEL", "Fuel"),
                            ("MAINTENANCE", "Maintenance"),
                            ("UTILITIES", "Utilities"),
                            ("TRANSPORT", "Transport"),
                            ("MISC", "Miscellaneous"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fiscal_year", models.IntegerField()),
                (
                    "month",
                    models.IntegerField(
                        blank=True,
                        help_text="1-12, or blank for the whole year",
                        null=True,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="farms.farm",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="finance.costcenter",
                    ),
                ),
            ],
            options={
                "ordering": ["-fiscal_year", "-month"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="finance.costcenter",
            ),
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("buyer", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("unit", models.CharField(blank=True, max_length=30)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="agronomy.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
