# Generated by Django 6.0.6 on 2026-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_crop_payment_is_advance_costcenter_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='bill_file',
            field=models.FileField(blank=True, upload_to='finance/bills/costcenters/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_file',
            field=models.FileField(blank=True, upload_to='finance/bills/payments/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_file',
            field=models.FileField(blank=True, upload_to='finance/bills/purchases/'),
        ),
    ]
