# Generated by Django 6.0.6 on 2026-06-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_costcenter_bill_file_payment_bill_file_and_more'),
        ('workforce', '0002_department_skill_availability_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments', to='workforce.employee'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='workforce.employee'),
        ),
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='workforce.employee'),
        ),
    ]
