# Generated by Django 6.0.6 on 2026-06-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_employee_purchase_employee_sale_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_file',
            field=models.FileField(blank=True, upload_to='finance/bills/expenses/'),
        ),
        migrations.AddField(
            model_name='sale',
            name='bill_file',
            field=models.FileField(blank=True, upload_to='finance/bills/sales/'),
        ),
    ]
