# Generated by Django 6.0.6 on 2026-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_bill_file_sale_bill_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='purchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
