# Generated by Django 6.0.6 on 2026-06-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_purchase_quantity_purchase_unit_purchase_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
