# Generated by Django 6.0.6 on 2026-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_purchase_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_advance',
            field=models.BooleanField(default=False, help_text='Advance payment'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
