# Generated by Django 5.2.15 on 2026-07-14 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0001_initial'),
        ('farms', '0006_farm_lat_lng_full_precision'),
        ('finance', '0009_remove_purchase_vendor_remove_expense_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='category',
            field=models.CharField(choices=[('CROP_SALE', 'Crop / Harvest Sale'), ('LIVESTOCK', 'Livestock / Dairy'), ('SUBSIDY', 'Subsidy'), ('RENT', 'Rent / Lease'), ('EQUIPMENT_SALE', 'Equipment Sale'), ('OTHER', 'Other')], default='CROP_SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='agronomy.crop'),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='name',
            field=models.CharField(blank=True, help_text='Label for this income entry', max_length=255),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='source_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(blank=True, choices=[('LABOUR', 'Labour'), ('INPUTS', 'Inputs'), ('FUEL', 'Fuel'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport'), ('ASSET', 'Asset'), ('MISC', 'Miscellaneous')], max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('LABOUR', 'Labour'), ('INPUTS', 'Inputs'), ('FUEL', 'Fuel'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport'), ('ASSET', 'Asset'), ('MISC', 'Miscellaneous')], default='MISC', max_length=15),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['source_type', 'source_id'], name='finance_exp_source__10102b_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['source_type', 'source_id'], name='finance_rev_source__bcfcb2_idx'),
        ),
    ]
