# Generated by Django 5.2.15 on 2026-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_backfill_finance_mirrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(blank=True, help_text='Label for this sale', max_length=255),
        ),
    ]
