# Generated by Django 5.2.15 on 2026-07-14 11:40

from django.conf import settings
from django.db import migrations, models


def dedupe_mirrors(apps, schema_editor):
    """Collapse duplicate mirror rows to one per (source_type, source_id).

    An earlier version of the mirror signal could create a second mirror when a
    source was edited, which then crashed update_or_create. Keep the oldest row
    for each linked source and delete the rest, so the unique constraint below
    can be created cleanly.
    """
    for label in ("Expense", "RevenueEntry"):
        Model = apps.get_model("finance", label)
        seen = {}
        dup_ids = []
        qs = (
            Model.objects.exclude(source_type="")
            .order_by("created_at")
            .values_list("id", "source_type", "source_id")
        )
        for pk, st, sid in qs:
            key = (st, sid)
            if key in seen:
                dup_ids.append(pk)
            else:
                seen[key] = pk
        if dup_ids:
            Model.objects.filter(id__in=dup_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0001_initial'),
        ('farms', '0006_farm_lat_lng_full_precision'),
        ('finance', '0012_sale_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Only data cleanup here. The UNIQUE constraints are added in 0014 — a
    # SEPARATE migration/transaction — because Postgres refuses to CREATE INDEX
    # in a transaction that already ran DELETEs ("pending trigger events").
    operations = [
        migrations.RunPython(dedupe_mirrors, migrations.RunPython.noop),
    ]
