# Generated by Django 5.2.15 on 2026-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_accountant_supervisor_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="user",
            name="aadhaar_photo",
            field=models.ImageField(blank=True, null=True, upload_to="aadhaar/"),
        ),
    ]
