# Generated by Django 5.2.16 on 2026-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restore_super_admin_farm_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='hashed_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
