# Generated by Django 5.2.16 on 2026-07-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_otp_hashed_code_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='hashed_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
