# Generated by Django 5.2.16 on 2026-07-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_otp_hashed_code_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
