# Generated by Django 5.2.15 on 2026-06-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Root task of a recurring series",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("ANNUAL", "Annual"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("ANNUAL", "Annual"),
                    ("ADHOC", "Ad-hoc"),
                ],
                default="ADHOC",
                max_length=10,
            ),
        ),
    ]
