# Generated by Django 5.2.15 on 2026-07-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0011_alter_attendance_status_null'),
        ('tasks', '0003_add_taskworksession_model'),
    ]

    operations = [
        # Add new status choices to existing Task model
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('ON_BREAK', 'On Break'), ('WAITING_APPROVAL', 'Waiting Approval'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20),
        ),

        # Create TaskExecution model
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('ON_BREAK', 'On Break'), ('WAITING_APPROVAL', 'Waiting Approval'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='ASSIGNED', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('working_seconds', models.IntegerField(default=0)),
                ('break_seconds', models.IntegerField(default=0)),
                ('current_timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_break_started_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('gps_start_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_start_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_break_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_break_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_complete_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_complete_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('completion_photo', models.ImageField(blank=True, null=True, upload_to='tasks/completion/')),
                ('completion_notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='workforce.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_task_executions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('task', 'employee')},
            },
        ),

        # Create TaskBreakLog model
        migrations.CreateModel(
            name='TaskBreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('break_ended_at', models.DateTimeField(blank=True, null=True)),
                ('break_duration_seconds', models.IntegerField(default=0)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_logs', to='tasks.taskexecution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_break_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Create TaskProgressLog model
        migrations.CreateModel(
            name='TaskProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tasks/progress/')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='tasks.taskexecution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_progress_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]