# Generated by Django 5.2.15 on 2026-07-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_execution_workflow'),
        ('workforce', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add work lifecycle fields to Task model
        migrations.AddField(
            model_name='task',
            name='before_work_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Add before work fields to TaskExecution
        migrations.AddField(
            model_name='taskexecution',
            name='before_work_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/before_work/'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='before_work_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='before_work_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='before_work_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='before_work_time',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Add break start fields
        migrations.AddField(
            model_name='taskexecution',
            name='break_start_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/break_start/'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='break_start_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='break_start_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='break_start_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Add break end fields
        migrations.AddField(
            model_name='taskexecution',
            name='break_end_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/break_end/'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='break_end_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='break_end_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='break_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Add timer tracking fields
        migrations.AddField(
            model_name='taskexecution',
            name='total_break_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='total_work_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='current_timer_seconds',
            field=models.IntegerField(default=0),
        ),

        # Add completion fields (rename/augment existing)
        migrations.AddField(
            model_name='taskexecution',
            name='completion_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='completion_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Create TaskActivity model
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('BEFORE_WORK', 'Before Work'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End'), ('DURING_WORK', 'During Work'), ('COMPLETED', 'Completed')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tasks/activities/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='workforce.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
                ('task_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.taskexecution')),
            ],
            options={
                'verbose_name': 'Task Activity',
                'verbose_name_plural': 'Task Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]