# Generated by Django 5.2.15 on 2026-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_work_lifecycle_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='address',
            field=models.TextField(blank=True, help_text='Auto-detected address from GPS'),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for DURING_WORK and COMPLETED'),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for break (BREAK_START)'),
        ),
    ]
