# Generated by Django 5.2.15 on 2026-06-17 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldactivity",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_activities",
                to="farms.field",
            ),
        ),
        migrations.CreateModel(
            name="ActivityPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("BEFORE", "Before Work"),
                            ("DURING", "During Work"),
                            ("COMPLETION", "Completion"),
                        ],
                        default="DURING",
                        max_length=12,
                    ),
                ),
                ("photo", models.ImageField(upload_to="field_activity/")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gps.fieldactivity",
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "created_at"],
            },
        ),
    ]
