# Generated by Django 6.0.6 on 2026-06-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_fieldactivity_field_activityphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='location_pings/'),
        ),
    ]
