# Generated by Django 5.2.15 on 2026-06-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0003_locationping_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationping",
            name="activity",
            field=models.CharField(
                choices=[
                    ("CHECKIN", "Check-in"),
                    ("CHECKOUT", "Check-out"),
                    ("TASK", "Task"),
                    ("PATROL", "Patrol"),
                    ("TRACK", "Track"),
                ],
                default="TRACK",
                max_length=10,
            ),
        ),
    ]
