# Generated by Django 6.0.6 on 2026-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_alter_locationping_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationping',
            name='activity',
            field=models.CharField(choices=[('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('DURING_WORK', 'During Work'), ('TASK', 'Task'), ('PATROL', 'Patrol'), ('TRACK', 'Track')], default='TRACK', max_length=15),
        ),
    ]
