# Generated by Django 5.2.15 on 2026-07-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0005_alter_locationping_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes submitted with this work proof ping'),
        ),
    ]
