# Generated by Django 5.2.15 on 2026-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0006_location_ping_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationping',
            name='activity',
            field=models.CharField(choices=[('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('DURING_WORK', 'During Work'), ('BREAK', 'Break'), ('RESUME', 'Resume'), ('TASK', 'Task'), ('PATROL', 'Patrol'), ('TRACK', 'Track')], default='TRACK', max_length=15),
        ),
    ]
