# Generated by Django 5.2.15 on 2026-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0009_geofence_center_full_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationping',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
