# Generated by Django 5.2.15 on 2026-06-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workforce",
            "0002_department_skill_availability_employee_department_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
