# Generated by Django 6.0.6 on 2026-07-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_add_is_active_field_to_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('LABOUR', 'Labour'), ('MANAGER', 'Manager')], default='LABOUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the employee is currently active/employed'),
        ),
    ]
