# Generated by Django 6.0.6 on 2026-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_add_manager_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('LABOUR', 'Labour'), ('MANAGER', 'Manager'), ('SUPER_ADMIN', 'Super Administrator')], default='LABOUR', max_length=20),
        ),
    ]
