# Generated by Django 5.2.15 on 2026-07-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_attendance_default_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from farm center in metres at check-in', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'Leave'), ('PRESENT_DONE', 'Present Done')], default='ABSENT', max_length=20),
        ),
    ]
