# Generated by Django 5.2.15 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_attendance_check_in_distance_and_more'),
    ]

    operations = [
        # Change status to allow NULL - attendance is created ONLY on check-in
        # No auto-creation of attendance rows
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'Leave'), ('PRESENT_DONE', 'Present Done')], default=None, max_length=20, null=True),
        ),
    ]