# Generated by Django 5.2.15 on 2026-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0011_alter_attendance_status_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='geofence_status',
            field=models.BooleanField(blank=True, help_text='True if GPS is inside farm geofence, False if outside, null if no GPS', null=True),
        ),
    ]
