# Generated by Django 5.2.15 on 2026-07-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_attendance_check_in_notes_attendance_check_out_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_address',
            field=models.TextField(blank=True, help_text='Auto-detected address from check-in GPS'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_address',
            field=models.TextField(blank=True, help_text='Auto-detected address from check-out GPS'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from farm center in metres at check-out', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_geofence_status',
            field=models.BooleanField(blank=True, help_text='True if GPS is inside farm geofence at check-out, False if outside, null if no GPS', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_seconds',
            field=models.IntegerField(default=0, help_text='Overtime seconds beyond regular working hours'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='working_seconds',
            field=models.IntegerField(default=0, help_text='Total working seconds for this attendance'),
        ),
    ]
