# Generated by Django 5.2.15 on 2026-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0013_attendance_enhanced_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per hour worked, used when wage_type is HOURLY', max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='wage_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Salary'), ('HOURLY', 'Hourly Wage')], default='MONTHLY', help_text='Whether pay is calculated per month (attendance-prorated) or per hour worked', max_length=20),
        ),
    ]
