# Generated by Django 5.2.15 on 2026-07-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_lat_lng_full_precision'),
        ('workforce', '0015_attendancemonthlysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='skill',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='farms.farm'),
        ),
    ]
