# Generated by Django 5.2.15 on 2026-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=200)),
                ('record_id', models.CharField(blank=True, default='', max_length=64)),
                ('operation', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('REFRESH', 'Refresh (whole worksheet)'), ('BACKFILL', 'Backfill (whole worksheet)')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed')], db_index=True, max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('error', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'sync log entry',
                'verbose_name_plural': 'sync log entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
